site_name: ""
theme:
  name: "material"
  language: "es"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode        

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:       
        icon: material/brightness-4
        name: Switch to system preference
        
  features:
    #- navigation.tabs
    - toc.integrate
    #- navigation.sections
    #- search.suggest
    #- search.highlight
    #- toggle

nav:
  - Sobre mi: index.md
  - Curriculum: curriculum.md