site_name: Jose San Martin
extra_css:
  - assets/stylesheets/extra.css
theme:
    name: material
    palette:
    - scheme: default
      primary: white
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Modo oscuro
    - scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Modo claro
plugins:
    - search
nav:
    - Home: index.md
    - CV: curriculum.md
    - Computational services: computational.md
    - Recommended bibliography: bibliography.md


    
    
    
